github.com:
    oauth_token: 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
    user: ohasanliUW
    git_protocol: ssh
    users:
        ohasanliUW:
            oauth_token: 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
